/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Comment: typeof import('./src/components/reply/comment.vue')['default']
    Commonnt: typeof import('./src/components/reply/commonnt.vue')['default']
    Commont: typeof import('./src/components/reply/commont.vue')['default']
    Datas: typeof import('./src/components/overview/datas.vue')['default']
    Gather: typeof import('./src/components/overview/gather.vue')['default']
    HeadBar: typeof import('./src/components/bar/HeadBar.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconAlarmOutline: typeof import('@yike-design/ui/es/components/svg-icon')['IconAlarmOutline']
    IconBulbOutline: typeof import('@yike-design/ui/es/components/svg-icon')['IconBulbOutline']
    IconCirclePlusOutline: typeof import('@yike-design/ui/es/components/svg-icon')['IconCirclePlusOutline']
    IconDeleteOutline: typeof import('@yike-design/ui/es/components/svg-icon')['IconDeleteOutline']
    IconMove2Fill: typeof import('@yike-design/ui/es/components/svg-icon')['IconMove2Fill']
    IconPlusOutline: typeof import('@yike-design/ui/es/components/svg-icon')['IconPlusOutline']
    IconSearchOutline: typeof import('@yike-design/ui/es/components/svg-icon')['IconSearchOutline']
    IconSettingsOutline: typeof import('@yike-design/ui/es/components/svg-icon')['IconSettingsOutline']
    Information: typeof import('./src/components/reply/information.vue')['default']
    Line: typeof import('./src/components/echarts/line.vue')['default']
    MenuBar: typeof import('./src/components/bar/MenuBar.vue')['default']
    Pie: typeof import('./src/components/echarts/pie.vue')['default']
    Reply: typeof import('./src/components/reply/reply.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Subset: typeof import('./src/components/subset/subset.vue')['default']
    SubsetManage: typeof import('./src/components/subset/subset-manage.vue')['default']
    TopTitle: typeof import('./src/components/bar/TopTitle.vue')['default']
    YkAvatar: typeof import('@yike-design/ui')['YkAvatar']
    YkBadge: typeof import('@yike-design/ui')['YkBadge']
    YkButtom: typeof import('@yike-design/ui')['YkButtom']
    YkButton: typeof import('@yike-design/ui')['YkButton']
    YkDrawer: typeof import('@yike-design/ui')['YkDrawer']
    YkInput: typeof import('@yike-design/ui')['YkInput']
    YkInputSearch: typeof import('@yike-design/ui')['YkInputSearch']
    YkModal: typeof import('@yike-design/ui')['YkModal']
    YkPagination: typeof import('@yike-design/ui')['YkPagination']
    YkPopconfirm: typeof import('@yike-design/ui')['YkPopconfirm']
    YkRadio: typeof import('@yike-design/ui')['YkRadio']
    YkRadioGroup: typeof import('@yike-design/ui')['YkRadioGroup']
    YkScro: typeof import('@yike-design/ui')['YkScro']
    YkScrollbar: typeof import('@yike-design/ui')['YkScrollbar']
    YkSearch: typeof import('@yike-design/ui')['YkSearch']
    YkSpace: typeof import('@yike-design/ui')['YkSpace']
    YkTable: typeof import('@yike-design/ui')['YkTable']
    YkTableColumn: typeof import('@yike-design/ui')['YkTableColumn']
    YkTag: typeof import('@yike-design/ui')['YkTag']
    YkText: typeof import('@yike-design/ui')['YkText']
    YkTheme: typeof import('@yike-design/ui')['YkTheme']
    YkTitle: typeof import('@yike-design/ui')['YkTitle']
  }
}
